spring:
  application:
    name: admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.25.137:5432/test_admin?useUnicode=true&characterEncoding=UTF-8
    username: test_admin_user
    password: test_admin_user

  data:
    redis:
      host: 192.168.25.137
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 40
          max-idle: 10
          max-wait: 3000
      password: 1qaz#EDC2wsx
server:
  port: 8088
  servlet:
    context-path: /test

mybatis:
  mapper-locations: classpath:/com/pg/**/dao/*.xml