spring:
  application:
    name: admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.25.137:5432/test_admin?useUnicode=true&characterEncoding=UTF-8
    username: test_admin_user
    password: test_admin_user

server:
  port: 8088
  servlet:
    context-path: /test

mybatis:
  mapper-locations: classpath:/com/pg/**/dao/*.xml
